config/routes.rb
FeedbackForHenri::Application.routes.draw do
  resources :projects do
    resources :answers
  end
  
  namespace :admin do
    resources :projects
  end
  
  root 'welcome#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :project
  belongs_to :role
  
  validates :role_id, :presence => true
  validates :score, :presence => true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :answers
  has_and_belongs_to_many :roles
  
  validates :key, :presence => true
  
  def to_param
    "#{id}-#{key}"
  end
  
  def net_promoter_score(role_id=nil)
    return calculate_nps(answers.where(:role_id => role_id)) if role_id
    calculate_nps(answers)
  end
  
  private
  def calculate_nps(selected_answers)
    return nil if selected_answers.empty?
    negatives = 0
    neutrals = 0
    positives = 0
    selected_answers.each do |answer|
      if answer.score >= 9
        positives = positives + 1
      elsif answer.score == 7 or answer.score == 8
        neutrals = neutrals + 1
      else
        negatives = negatives + 1
      end
    end
    100 * (-negatives + positives).to_f / (negatives + neutrals + positives)
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  validates :name, :presence => true
end

app/models/status.rb
class Status < ActiveRecord::Base
  validates :name, :presence => true
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
  end
end

app/controllers/answers_controller.rb
# encoding: UTF-8
class AnswersController < ApplicationController
  def index
  end
  
  def new
    @project = Project.find(params[:project_id])
    @answer = @project.answers.new
  end
  
  def create
    @project = Project.find(params[:project_id])
    @answer = Answer.new(params.require(:answer).permit(:project_id, :role_id, :score, :comment))
    if @answer.save
      send_answer_email @answer
      redirect_to project_answers_path
    else
      flash[:error] = 'Vastaus puuttuu'
      render :new
    end
  end
  
  private
  def send_answer_email(answer)
    begin
      AnswerMailer.answered(@answer).deliver
    rescue => e
      p "Failed to send answer email (#{@answer.inspect}): #{e}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
    redirect_to new_project_answer_path(@project)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/projects/show.html.erb
<h1>Projekti: <%= @project.key %></h1>
<input type="text" value="<%= new_project_answer_url(@project) %>" size="100"/>
<h2>Vastaukset</h2>
<ul>
  <% @project.answers.order('created_at asc').each do |answer| %>
    <li><%= answer.score %> (<%= answer.role.name %>, <%= answer.created_at.strftime('%d.%m.%Y %H:%M:%S') %>)</li>
    <% unless answer.comment.blank? %>
      <ul>
        <li><%= answer.comment %></li>
      </ul>
    <% end %>
  <% end %>
</ul>
<h2>Net promoter score</h2>
<table>
  <tr>
    <% unless @project.roles.count == 1 %>
      <th>Rooli</th>
    <% end %>
    <th>Kpl</th>
    <th>Net promoter score</th>
  </tr>
  <tr>
    <% unless @project.roles.count == 1 %>
      <td>Kaikki</td>
    <% end %>
    <td class="center"><%= @project.answers.count %></td>
    <td class="center"><%= @project.net_promoter_score.to_i %></td>
  </tr>
<% unless @project.roles.count == 1 %>
  <% Role.all.each do |role| %>
    <tr>
      <td><%= role.name %></td>
      <td class="center"><%= @project.answers.where(role: role).count %></td>
      <td class="center"><%= @project.net_promoter_score(role.id).to_i %></td>
    </tr>
  <% end %>
<% end %>
</table>

app/views/answers/index.html.erb
Kiitos palautteesta!

app/views/answers/new.html.erb
<h1>Palautetta Henrille</h1>

<p>
Arvostan suuresti palautettasi tekemästäni työstä.<br/>
Pyydän sinua vastaamaan alla olevaan kolmeen kysymykseen.<br/>
t: Henri
</p>
<hr/>

<div class="error"><%= flash[:error] %></div>

<%= form_for [@project, @answer] do |f| %>
  <%= f.hidden_field :project_id %>
  <% roles = @project.roles %>
  <% if roles.count == 1 %>
    <%= f.hidden_field :role_id, value: roles.first.id %>
  <% elsif roles.count == 0 %>
    <% raise "No roles for the project!" %>
  <% else %>
    <div class="question">
      <%= f.label :role_id, 'Palautteen antajan rooli' %><br/>
      <% @project.roles.each do |role| %>
        <%= f.radio_button :role_id, role.id %><%= role.name %>
      <% end %>
    </div>
  <% end %>
  <div class="question">
    <%= f.label :score, @project.question %><br/>
    <% 0.upto(10) do |i| %>
      <%= f.radio_button :score, i %><%= i %>
    <% end %>
  </div>
  <div class="question">
    <%= f.label :comment, 'Jos annoit vähemmän kuin 10, missä minun kannattaisi parantaa?' %><br/>
    <%= f.text_area :comment, :rows => 10, :cols => 50 %>
  </div>
  <%= submit_tag 'Lähetä palaute' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Feedback for Henri</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="content">
  <%= yield %>
</div>

</body>
</html>

app/views/projects/show.html.erb
<h1>Palautetta Henrille</h1>

<p>
Arvostan suuresti palautettasi tekemästäni työstä. Pyydän sinua vastaamaan alla olevaan kolmeen kysymykseen.
t: Henri
</p>

<%= form_for @answer do |f| %>
  <%= f.hidden_field :project_id %>
  <div>
    <%= f.label :status_id, 'Asema' %><br/>
    <% @statuses.each do |status| %>
      <%= f.radio_button :status_id, status.id %><%=status.name%>
    <% end %>
  </div>
  <div>
    <%= f.label :score, 'Kuinka todennäköisesti suosittelisit minua kollegallesi johonkin toiseen projektiin?' %><br/>
    <% 0.upto(10) do |i| %>
      <%= f.radio_button :score, i %><%= i %>
    <% end %>
  </div>
  <div>
    <%= f.label :comment, 'Vapaa palaute (ei pakollinen)' %><br/>
    <%= f.text_area :comment, :rows => 10, :cols => 50 %>
  </div>
  <%= submit_tag 'Lähetä palaute' %>
<% end %>

app/views/welcome/index.html.erb
<a href="http://www.karhatsu.com">www.karhatsu.com</a>